### ISSUE TITLE
Why only vtt and not srt from url? 

### ISSUE THREAD

**Issue by pharshdev** [snaeji/video_player-0.10.1-3#1]

**Comment by snaeji** [comment]
Hey, If you want to change it manually you can change VTT to SRT here:

https://github.com/snaeji/video_player-0.10.1-3/blob/master/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java#L122

But since my use case was only vtt i didn't add a variable in the controller but you're welcome to make a pull request.

**Comment by pharshdev** [comment]
Already did thanks.
